# Generated by Django 3.2.11 on 2022-01-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190422_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogPageTag',
        ),
    ]
